{% set name = "dedupe" %}
{% set version = "2.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0320b39899d489a760c1e0e9e67a526698531f67d03129ac3f76db778f09737
  patches:
    - patches/0001-fix-dependencies.patch

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - cython
    - pip
    - setuptools >=63
    - wheel
  run:
    - python
    - scikit-learn
    - affinegap >=1.3
    - btrees >=4.1.4
    - categorical-distance >=1.9
    # - dedupe-variable-datetime
    - doublemetaphone
    - haversine >=0.4.1
    - highered >=0.2.0
    - dedupe_levenshtein_search
    - numpy >=1.20
    - simplecosine >=1.2
    - typing-extensions
    - zope.index

test:
  imports:
    - dedupe
    - dedupe.variables
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dedupeio/dedupe
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: |
    A python library for accurate and scalable fuzzy matching, record
    deduplication and entity-resolution.
  description: |
    dedupe is a python library that uses machine learning to perform fuzzy matching,
    deduplication and entity resolution quickly on structured data.
  doc_url: https://docs.dedupe.io
  dev_url: https://github.com/dedupeio/dedupe
extra:
  recipe-maintainers:
    - osamples
    - izahn
