{% set name = "dedupe" %}
{% set version = "2.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dedupe-{{ version }}.tar.gz
  sha256: 4d3d313722400220410e6994c7bb40e04b5b6b93636ea6310839e21a71c06431

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - affinegap >=1.3
    - btrees >=4.1.4
    - categorical-distance >=1.9
    - dedupe-hcluster
    - dedupe-variable-datetime
    - doublemetaphone
    - fastcluster
    - haversine >=0.4.1
    - highered >=0.2.0
    - levenshtein-search
    - numpy >=1.13
    - python
    - rlr >=2.4.3
    - simplecosine >=1.2
    - typing-extensions
    - zope.index

test:
  imports:
    - dedupe
    - dedupe.variables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dedupeio/dedupe
  summary: A python library for accurate and scaleable data deduplication and entity-resolution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
